name: Master Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Artifact Caching
        uses: actions/cache@v2.1.1
        with:
          path: /cache
          key: var
          
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build Taika/Taika.md.sln
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: Taika/

